/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hx_hexintegrated_HexNative */

#ifndef _Included_com_hx_hexintegrated_HexNative
#define _Included_com_hx_hexintegrated_HexNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hx_hexintegrated_HexNative
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hx_hexintegrated_HexNative_encryption
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hx_hexintegrated_HexNative
 * Method:    encryptionByCusLen
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hx_hexintegrated_HexNative_encryptionByCusLen
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
