/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hexing_ndktest_Java */

#ifndef _Included_com_hexing_ndkDemo_Java2CJNI
#define _Included_com_hexing_ndkDemo_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
